# ==============================
# Application Info
# ==============================
spring.application.name=auth-service
server.port=9091

# ==============================
# JWT Settings
# ==============================
jwt.secret=7LB+f3g8QklfYk8cPz+WZQKxg2Xjs1cXjT1K7ZoytwA=
jwt.expiration=3600000
jwt.issuer=auth-service
jwt.audience=education-portal
# ==============================
# GitHub OAuth2 Login
# ==============================
spring.security.oauth2.client.registration.github.client-id=Ov23li1k5f2zFt1fQHfI
spring.security.oauth2.client.registration.github.client-secret=3e187b7a1a2d37940b900c7a1ef30f4b69d8da95
spring.security.oauth2.client.registration.github.scope=read:user,user:email
spring.security.oauth2.client.registration.github.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.github.client-name=GitHub

# ==============================
# OAuth2 Provider (GitHub)
# ==============================
spring.security.oauth2.client.provider.github.authorization-uri=https://github.com/login/oauth/authorize
spring.security.oauth2.client.provider.github.token-uri=https://github.com/login/oauth/access_token
spring.security.oauth2.client.provider.github.user-info-uri=https://api.github.com/user
spring.security.oauth2.client.provider.github.user-name-attribute=id
